# src/rhosocial/activerecord/backend/impl/clickhouse/expression/__init__.py
"""
ClickHouse-specific expression classes.

This module provides expression classes that are specific to ClickHouse, such as
LOAD DATA INFILE, JSON_TABLE, JSON functions, spatial functions, vector
functions, MATCH...AGAINST expressions, row-level locking expressions,
and JSON Duality View expressions.

Directory structure:
- load_data.py      - LOAD DATA INFILE expression
- json_table.py    - JSON_TABLE expression
- json.py           - JSON function expressions
- spatial.py         - Spatial function expressions
- vector.py          - Vector function expressions (ClickHouse 9.0+)
- match_against.py - MATCH...AGAINST expression
- locking.py        - Row-level locking expressions (FOR UPDATE, FOR SHARE)
- json_duality_view.py - JSON Duality View expressions (ClickHouse 9.7+)
- types.py          - ClickHouse-specific DataType subclasses for DDL
"""

from .load_data import ClickHouseLoadDataExpression, LoadDataOptions
from .json_table import ClickHouseJSONTableExpression, JSONTableColumn, NestedPath
from .json import (
    ClickHouseJSONExtractExpression,
    ClickHouseJSONObjectExpression,
    ClickHouseJSONArrayExpression,
    ClickHouseJSONContainsExpression,
)
from .spatial import (
    ClickHouseSTGeomFromTextExpression,
    ClickHouseSTDistanceExpression,
    ClickHouseSTWithinExpression,
    ClickHouseSTContainsExpression,
)
from .vector import (
    ClickHouseVectorExpression,
    ClickHouseDistanceEuclideanExpression,
    ClickHouseDistanceCosineExpression,
    ClickHouseDistanceDotExpression,
)
from .match_against import ClickHouseMatchAgainstExpression, MatchAgainstMode
from .locking import ClickHouseForUpdateClause, ClickHouseLockStrength
from .json_duality_view import (
    CreateJsonDualityViewExpression,
    DropJsonDualityViewExpression,
    DualityObjectSpec,
    DualityColumnMapping,
    DualityNestedMapping,
    DualityViewDMLTag,
)
from .optimizer_hint import (
    ClickHouseOptimizerHintExpression,
    SetVarHint,
    OptimizerHintType,
)
from .partition import (
    ClickHousePartitionStrategy,
    ClickHousePartitionClause,
    ClickHousePartitionMaxValue,
    ClickHousePartitionValue,
    ClickHousePartitionDefinition,
    ClickHousePartitionByRange,
    ClickHousePartitionByRangeColumns,
    ClickHousePartitionByList,
    ClickHousePartitionByListColumns,
    ClickHousePartitionByHash,
    ClickHousePartitionByKey,
    ClickHouseAddPartitionExpression,
    ClickHouseDropPartitionExpression,
    ClickHouseTruncatePartitionExpression,
    ClickHouseReorganizePartitionExpression,
    ClickHouseExchangePartitionExpression,
    ClickHouseRemovePartitioningExpression,
    ClickHouseCoalescePartitionExpression,
    ClickHouseAnalyzePartitionExpression,
    ClickHouseCheckPartitionExpression,
    ClickHouseOptimizePartitionExpression,
    ClickHouseRebuildPartitionExpression,
    ClickHouseRepairPartitionExpression,
    ClickHouseGetPartitionsExpression,
    ClickHouseSubpartitionStrategy,
    ClickHouseSubpartitionDefinition,
    ClickHouseSubpartitionClause,
)
from .partition_lifecycle import (
    ClickHouseAddPartitionHelper,
    ClickHouseAddSubpartitionHelper,
    ClickHouseCoalescePartitionHelper,
    ClickHouseDropOldestPartitionHelper,
    ClickHouseReorganizePartitionHelper,
)
from .rename_table import ClickHouseRenameTableExpression
from .table_statement import ClickHouseTableExpression, ClickHouseValuesExpression
from .maintenance import (
    ClickHouseAnalyzeTableExpression,
    ClickHouseCheckTableExpression,
    ClickHouseChecksumTableExpression,
    ClickHouseOptimizeTableExpression,
    ClickHouseRepairTableExpression,
    CheckTableOption,
    ChecksumTableOption,
    RepairTableOption,
    NoWriteToBinlogOption,
)
from .routine import (
    ClickHouseCallExpression,
    ClickHouseCreateProcedureExpression,
    ClickHouseDropProcedureExpression,
    ClickHouseCreateFunctionExpression,
    ClickHouseDropFunctionExpression,
)
from .load_xml import ClickHouseLoadXMLEXpression, LoadXMLPriority, LoadXMLConflictMode
from .admin import (
    ClickHouseCacheIndexExpression,
    ClickHouseLoadIndexIntoCacheExpression,
    ClickHouseFlushExpression,
    FlushOption,
    ClickHouseResetExpression,
    ResetOption,
    ClickHouseInstallComponentExpression,
    ClickHouseUninstallComponentExpression,
    ClickHouseInstallPluginExpression,
    ClickHouseUninstallPluginExpression,
    ClickHouseCloneExpression,
    ClickHouseRestartExpression,
    ClickHouseBinlogExpression,
    ClickHouseHandlerOpenExpression,
    ClickHouseHandlerReadExpression,
    ClickHouseHandlerCloseExpression,
    HandlerReadMode,
    ClickHouseDoExpression,
    ClickHouseKillExpression,
    KillTarget,
    ClickHouseShutdownExpression,
    ClickHouseHelpExpression,
    AccountSpec,
    GrantPrivilege,
    ClickHouseCreateUserExpression,
    ClickHouseDropUserExpression,
    ClickHouseGrantExpression,
    ClickHouseRevokeExpression,
)

# DataType subclasses for DDL
from .types import (
    ClickHouseBigIntType,
    ClickHouseBinaryType,
    ClickHouseBitType,
    ClickHouseBlobType,
    ClickHouseEnumType,
    ClickHouseGeometryCollectionType,
    ClickHouseGeometryType,
    ClickHouseIntType,
    ClickHouseLineStringType,
    ClickHouseLongBlobType,
    ClickHouseLongTextType,
    ClickHouseMediumBlobType,
    ClickHouseMediumTextType,
    ClickHouseMultiLineStringType,
    ClickHouseMultiPointType,
    ClickHouseMultiPolygonType,
    ClickHousePointType,
    ClickHousePolygonType,
    ClickHouseSetType,
    ClickHouseSmallIntType,
    ClickHouseTextType,
    ClickHouseTinyBlobType,
    ClickHouseTinyIntType,
    ClickHouseTinyTextType,
    ClickHouseVarBinaryType,
    ClickHouseVectorType,
    ClickHouseYearType,
)

__all__ = [
    "ClickHouseLoadDataExpression",
    "LoadDataOptions",
    "ClickHouseJSONTableExpression",
    "JSONTableColumn",
    "NestedPath",
    "ClickHouseJSONExtractExpression",
    "ClickHouseJSONObjectExpression",
    "ClickHouseJSONArrayExpression",
    "ClickHouseJSONContainsExpression",
    "ClickHouseSTGeomFromTextExpression",
    "ClickHouseSTDistanceExpression",
    "ClickHouseSTWithinExpression",
    "ClickHouseSTContainsExpression",
    "ClickHouseVectorExpression",
    "ClickHouseDistanceEuclideanExpression",
    "ClickHouseDistanceCosineExpression",
    "ClickHouseDistanceDotExpression",
    "ClickHouseMatchAgainstExpression",
    "MatchAgainstMode",
    "ClickHouseForUpdateClause",
    "ClickHouseLockStrength",
    "CreateJsonDualityViewExpression",
    "DropJsonDualityViewExpression",
    "DualityObjectSpec",
    "DualityColumnMapping",
    "DualityNestedMapping",
    "DualityViewDMLTag",
    "ClickHouseOptimizerHintExpression",
    "SetVarHint",
    "OptimizerHintType",
    "ClickHousePartitionStrategy",
    "ClickHousePartitionClause",
    "ClickHousePartitionMaxValue",
    "ClickHousePartitionValue",
    "ClickHousePartitionDefinition",
    "ClickHousePartitionByRange",
    "ClickHousePartitionByRangeColumns",
    "ClickHousePartitionByList",
    "ClickHousePartitionByListColumns",
    "ClickHousePartitionByHash",
    "ClickHousePartitionByKey",
    "ClickHouseAddPartitionExpression",
    "ClickHouseDropPartitionExpression",
    "ClickHouseTruncatePartitionExpression",
    "ClickHouseReorganizePartitionExpression",
    "ClickHouseExchangePartitionExpression",
    "ClickHouseRemovePartitioningExpression",
    "ClickHouseCoalescePartitionExpression",
    "ClickHouseAnalyzePartitionExpression",
    "ClickHouseCheckPartitionExpression",
    "ClickHouseOptimizePartitionExpression",
    "ClickHouseRebuildPartitionExpression",
    "ClickHouseRepairPartitionExpression",
    "ClickHouseSubpartitionStrategy",
    "ClickHouseSubpartitionDefinition",
    "ClickHouseSubpartitionClause",
    "ClickHouseRenameTableExpression",
    "ClickHouseTableExpression",
    "ClickHouseValuesExpression",
    "ClickHouseAnalyzeTableExpression",
    "ClickHouseCheckTableExpression",
    "ClickHouseChecksumTableExpression",
    "ClickHouseOptimizeTableExpression",
    "ClickHouseRepairTableExpression",
    "CheckTableOption",
    "ChecksumTableOption",
    "RepairTableOption",
    "NoWriteToBinlogOption",
    "ClickHouseCallExpression",
    "ClickHouseCreateProcedureExpression",
    "ClickHouseDropProcedureExpression",
    "ClickHouseCreateFunctionExpression",
    "ClickHouseDropFunctionExpression",
    "ClickHouseLoadXMLEXpression",
    "LoadXMLPriority",
    "LoadXMLConflictMode",
    "ClickHouseCacheIndexExpression",
    "ClickHouseLoadIndexIntoCacheExpression",
    "ClickHouseFlushExpression",
    "FlushOption",
    "ClickHouseResetExpression",
    "ResetOption",
    "ClickHouseInstallComponentExpression",
    "ClickHouseUninstallComponentExpression",
    "ClickHouseInstallPluginExpression",
    "ClickHouseUninstallPluginExpression",
    "ClickHouseCloneExpression",
    "ClickHouseRestartExpression",
    "ClickHouseBinlogExpression",
    "ClickHouseHandlerOpenExpression",
    "ClickHouseHandlerReadExpression",
    "ClickHouseHandlerCloseExpression",
    "HandlerReadMode",
    "ClickHouseDoExpression",
    "ClickHouseKillExpression",
    "KillTarget",
    "ClickHouseShutdownExpression",
    "ClickHouseHelpExpression",
    "AccountSpec",
    "GrantPrivilege",
    "ClickHouseCreateUserExpression",
    "ClickHouseDropUserExpression",
    "ClickHouseGrantExpression",
    "ClickHouseRevokeExpression",
    # DataType subclasses for DDL
    "ClickHouseBigIntType",
    "ClickHouseBinaryType",
    "ClickHouseBitType",
    "ClickHouseBlobType",
    "ClickHouseEnumType",
    "ClickHouseGeometryCollectionType",
    "ClickHouseGeometryType",
    "ClickHouseIntType",
    "ClickHouseLineStringType",
    "ClickHouseLongBlobType",
    "ClickHouseLongTextType",
    "ClickHouseMediumBlobType",
    "ClickHouseMediumTextType",
    "ClickHouseMultiLineStringType",
    "ClickHouseMultiPointType",
    "ClickHouseMultiPolygonType",
    "ClickHousePointType",
    "ClickHousePolygonType",
    "ClickHouseSetType",
    "ClickHouseSmallIntType",
    "ClickHouseTextType",
    "ClickHouseTinyBlobType",
    "ClickHouseTinyIntType",
    "ClickHouseTinyTextType",
    "ClickHouseVarBinaryType",
    "ClickHouseVectorType",
    "ClickHouseYearType",
]
